POST http://localhost:5000/api/v1/login
Content-Type: application/json

{
  "userId": "001",
  "passWord": "qwerty"
}

###
POST http://localhost:5000/api/v1/login
Content-Type: application/json

{
  "userId": "002",
  "passWord": "asdfgh"
}

###
GET http://localhost:5000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMDAwMSIsImlhdCI6MTU4NzE5NjM1MywiZXhwIjoxNTg3MTk3NTUzfQ.ejXFndLlJizSt7K3Szn4_qkwioNG_rGB90gd-ORAknw
