POST http://localhost:5000/api/v1/login
Content-Type: application/json

{
  "userId": "00001",
  "passWord": "qwerty"
}

###
POST http://localhost:5000/api/v1/login
Content-Type: application/json

{
  "userId": "00002",
  "passWord": "asdfgh"
}

###
GET http://localhost:5000/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMDAwMSIsImlhdCI6MTU4NzAwMDE2NiwiZXhwIjoxNTg3MDAxMzY2fQ.sx7gma9MU2Wh-fw9L60-mgmM_7TlMWKUhmg7lKIRCXs
